import type { NextPage, NextPageContext } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { c1 } from "../data/index";
import codd from "../data/component1.json";
import Example from "../components/pieGraph";
import axios from "axios"
import GroupBar from "../components/groupBar";
import ParentSize from "@visx/responsive/lib/components/ParentSize";

const Home: NextPage = ({ pieData, groupBarData }) => {
  // console.log("cdlnc", c1);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">React.js!</a>
        </h1>
        <div>
          <Example pieData={pieData.c2} />
          {/* <ParentSize>{({ width, height }) => <GroupBar gdata={groupBarData.c3} width={width} height={height} />}</ParentSize> */}
          <GroupBar gdata={groupBarData.c3} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps = async (ctx: NextPageContext) => {
  const c2 = await axios.get("http://localhost:3000/api/c2");
  const c3 = await axios.get("http://localhost:3000/api/c3");
  const pieData = c2.data;

  const groupBarData = c3.data;


  return {
    props: {
      pieData, groupBarData
    }
  };
};

export default Home;
